### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by wwwwelton** [paulo-santana/ft_transcendence#89]
- [x] - kick user disconnect, needs to disconnect user from specific room only
- [x] - remove duplicated users messages from direct message page
- [ ] - <s>add leave button in community and inside channel page</s>
- [x] - check if notifcation is working
- [ ] - <s>check message sockets</s>
- [x] - dynamic match type
- [ ] - <s>change send message to submit form</s>
- [x] - enter send channel/dm message
- [x] - check user join feat (if user join in channel 2, user shows in channel 1 user list)
- [x] - improve channel listing refresh list (on delete channel needs update real time)
